### ISSUE TITLE
Error from security filter on K8s

### ISSUE THREAD

**Issue by nischals-capsrx** [getfider/fider#1033]
Hello, 

While attempting to use Fider in K8S environment in single hosted mode(default), we are getting this error - 
Requested hostname '10.31.154.86' does not match environment HOST_DOMAIN 'fider.x.y.com'. It looks like the c.Request.URL.Hostname() here - https://github.com/getfider/fider/blob/d5342e86ee9dbd0a8357f1299014ee64dbdae25f/app/middlewares/security.go#L22 is resolving to the Pod IP which is ephemeral and causes the error, although it works on localhost. We've attempted to use HOST_MODE to be a value that is NOT "single" but then that leads to a 404 on trying to access the homepage.

Is there any specific configuration that should be attempted, or any environment variable that should be set to avoid it. Also it would be helpful to understand what HOST_MODE means between "single" and everything else. Appreciate an early response.

Thanks

**Comment by goenning** [comment]
Seems like you have a proxy which is not setting the Host header. I'm not very familiar with k8s or your setup, but have a look at how you can do that.

Essentially, if there's a proxy in front of Fider, it'll need to forward the Host header

**Comment by JianleiZhang** [comment]
maby this will help you.
``` yaml
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              httpHeaders:
                - name: Host
                  value: feedback.scdevops-nonprod.hycs.sitc
            initialDelaySeconds: 10
            timeoutSeconds: 10
```
