### ISSUE TITLE
Any plans to write deploy instructions for Render (or other Heroku alternatives)?

### ISSUE THREAD

**Issue by rampatra** [getfider/fider#1107]
Now that Heroku free tier is gone, many would want to move to other providers still offering free tiers, one of them being Render. So, a deploy instruction page (similar to [Deploy on Heroku](https://fider.io/docs/hosting-on-heroku)) would be beneficial.

**Comment by rampatra** [comment]
I actually went ahead and tried to write my own render.yaml file:
```
services:
  - type: web
    name: presentify-ideas
    env: go
    repo: https://github.com/Compzets/presentify-ideas.git
    buildCommand: npm ci
    startCommand: ./fider migrate && ./fider
```

But this doesn't work. I get `bash: ./fider: No such file or directory` error. I tried changing the `startCommand` to `./bin/fider migrate && ./bin/fider` but no luck.
