### ISSUE TITLE
Black White Screen on Sign-Up Page after installing with Docker

### ISSUE THREAD

**Issue by dukeseb** [getfider/fider#1165]
These are the steps that I went through and everything appears to be working according to "docker-compose logs app"

Here are the steps that I went through hopefully someone can give me an idea where to look

Install Ubuntu LTS

install docker engine
`sudo snap install docker`

install docker compose
`sudo apt install docker-compose`

`mkdir /var/fider`

`nano /var/fider/docker-compose.yml`

**<docker-compose.yml>**
                               
```
version: '2'
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "80:3000"
    environment:
      # Public Host Name
      BASE_URL: http://localhost

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-En>
      JWT_SECRET: secret

      # From which account e-mails will be sent
      EMAIL_NOREPLY: sbob@bob.com

      EMAIL_SMTP_HOST: smtp.bob.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: sbob@bob.com
      EMAIL_SMTP_PASSWORD: 452345345
      EMAIL_SMTP_ENABLE_STARTTLS: 'true'
```

`cd /var/fider`

`docker-compose pull`

`sudo docker-compose up -d`
