### ISSUE TITLE
[HELP] Running Fider Docker Setup Behind a Reverse Proxy

### ISSUE THREAD

**Issue by mpenchenat93** [getfider/fider#1235]
Hello,

Is the Fider Docker setup compatible with usage behind a reverse proxy? 

After numerous attempts at modifying my Docker(-Compose) configuration, I haven't been able to get Fider working. 

Could you help me?

```
version: "3.3"
services:
  caddy-gen:
    container_name: caddy-gen
    image: "wemakeservices/caddy-gen:latest"
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - prod_network

  db:
    restart: always
    image: postgres:12
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "80:3000"
    environment:
      BASE_URL: http://localhost
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable
      JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE
      EMAIL_NOREPLY: noreply@yourdomain.com
    labels:
      virtual.host: "fider.yourdomain.com"
      virtual.port: "3000"
      virtual.tls-email: "admin@yourdomain.com"

volumes:
  caddy-certificates:
    driver: local

networks:
  prod_network:
    driver: bridge

```

I have the impression that this Docker setup isn't designed to work behind a reverse proxy. 

It seems to work either:  
- Directly with HTTP;  
- Or directly with HTTPS via Nginx, for example.  

But HTTP to HTTPS through a reverse proxy doesn’t seem to work.  

Am I mistaken?

---

Thank you, 

Merry Christmas!
