### ISSUE TITLE
[BUG]  Self Certificate not found on Docker Desktop for Windows

### ISSUE THREAD

**Issue by swelcom** [getfider/fider#1241]
**Fider Cloud or Self Hosted**
Self Hosted: Stable, Latest 
Docker Desktop for Windows v4.37.1

**Describe the bug**
If I want to specify my own certificate as described in the docs, the Docker app cannot be started, the log says the following:

```
app-1 | panic: Error Trace:
app-1 | - failed to start server (app/pkg/web/engine.go:166)
app-1 | - open etc/cert.crt: no such file or directory
app-1 |
app-1 | goroutine 24 [running]:
app-1 | github.com/getfider/fider/app/pkg/web.(*Engine).Start(0xc00042c1c0, {0xc000014cf4, 0x5})
app-1 | /server/app/pkg/web/engine.go:166 +0xdc5
app-1 | created by github.com/getfider/fider/app/cmd.RunServer in goroutine 1
app-1 | /server/app/cmd/server.go:53 +0x35c
```

This is what my docker-compose.yml looks like:

```
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: ***
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "444:3000"
    environment:
      # Certificates
      SSL_CERT: cert.crt
      SSL_CERT_KEY: thekey.key
      # Public Host Name
      BASE_URL: https://localhost
      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://fider:***@db:5432/fider?sslmode=disable
      # Generate a secure secret, for example using https://jwtsecret.com
      JWT_SECRET: ***
      # From which account e-mails will be sent
      EMAIL_NOREPLY: ***
      EMAIL_SMTP_HOST: ***
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: ***
      EMAIL_SMTP_PASSWORD: ***
      EMAIL_SMTP_ENABLE_STARTTLS: 'true'
    volumes:
      - /var/fider/etc:/app/etc
```
