### ISSUE TITLE
[BUG] Fatal Error on Startup

### ISSUE THREAD

**Issue by marco-studer-srf** [getfider/fider#1295]
**Fider Cloud or Self Hosted**
Using self-hosted Docker image: **stable**

**Describe the bug**
When starting up the Docker Compose file, I get the following error in a loop:
```
#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffe7328a8b0Aborted (core dumped)


#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7fff1746c0a0Aborted (core dumped)


#
# Fatal error in , line 0
# Check failed: Start().
#
#
#
#FailureMessage Object: 0x7ffcbcd14db0Aborted (core dumped)
```

**To Reproduce**
Docker compose file:
```yml
services:
  fider:
    container_name: fider
    restart: unless-stopped
    image: getfider/fider:stable
    networks:
      - database
    env_file:
      - .env

networks:
  database:
    external: true
```
**.env:**

```
BASE_URL=https://abc.com

EMAIL_NOREPLY=https://noreply@abc.com
EMAIL_SMTP_HOST=smtp.sendgrid.net
EMAIL_SMTP_PORT=587
EMAIL_SMTP_USERNAME=apikey
EMAIL_SMTP_PASSWORD=xxx
EMAIL_SMTP_ENABLE_STARTTLS=true

JWT_SECRET=xxx
DATABASE_URL=postgres://fider:xxx@postgres:5432/fider
```

Database is running in `postgres` container. User `fider` and database `fider` exist.

**Expected behavior**
Startup withou error.

**Screenshots**

**Additional context**
