### ISSUE TITLE
Can't send mail

### ISSUE THREAD

**Issue by rtkachuk** [getfider/fider#387]
Hello there! I'm using Fider, and get strange problem: mail was not sent.

I want use my own postfix service on local machine, so my config is:

```
version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: pass

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "127.0.0.1:9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: development
      
      # Connection string to the PostgreSQL database. 
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://fider:pass@db:5432/fider?sslmode=disable
      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: mysecret

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: myhost@mydomain

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: localhost
      EMAIL_SMTP_PORT: 25
      #EMAIL_SMTP_USERNAME: null
      #EMAIL_SMTP_PASSWORD: null
      
      ###
      # OPTIONAL
      #
      # Following settings are optional
      ###

      # Social OAuth: 
      # Read more on https://getfider.com/docs/configuring-oauth/

      # Facebook
      # OAUTH_FACEBOOK_APPID: <fb_app_id>
      # OAUTH_FACEBOOK_SECRET: <fb_app_secret>

      # Google
      # OAUTH_GOOGLE_CLIENTID: <google_app_id>
      # OAUTH_GOOGLE_SECRET: <google_app_secret>

      # GitHub
      # OAUTH_GITHUB_CLIENTID: <github_client_id>
      # OAUTH_GITHUB_SECRET: <github_secret>

    depends_on:
      - db
```

So, when I tried to register - popup message "Sent message" appeared, but no message sent. Also no logs were on the console.

I'm also tried to use gmail - no luck.
