### ISSUE TITLE
pq: Could not detect default username. Please provide one explicitly

### ISSUE THREAD

**Issue by DougBeney** [getfider/fider#650]
On Ubuntu 18.04. Tried on both my desktop and server with same result.

```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

I get a bunch of errors that look like this:

```
app_1  | ERROR [2018-11-20T17:29:45Z] [MIGRATE] [I7K14VTeqw5ACfDcTlDl5xzISu31swhm] Error Trace: 
app_1  | - failed to open transaction (app/pkg/log/database/logger.go:126)
app_1  | - failed to start new transaction (app/pkg/dbx/dbx.go:59)
app_1  | - pq: Could not detect default username. Please provide one explicitly
```

My Config:

```
version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: test123

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: production
      
      # Connection string to the PostgreSQL database. 
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://fider:test123:5432/fider?sslmode=disable
      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: ADFASDFADFASDFADFASDF

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: hello@domain.org

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: MYCREDENTIALS
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: MYCREDENTIALS
      EMAIL_SMTP_PASSWORD: MYCREDENTIALS
      
      ###
      # OPTIONAL
      #
      # Following settings are optional
      ###

      # Social OAuth: 
      # Read more on https://getfider.com/docs/configuring-oauth/

      # Facebook
      # OAUTH_FACEBOOK_APPID: <fb_app_id>
      # OAUTH_FACEBOOK_SECRET: <fb_app_secret>

      # Google
      # OAUTH_GOOGLE_CLIENTID: <google_app_id>
      # OAUTH_GOOGLE_SECRET: <google_app_secret>

      # GitHub
      # OAUTH_GITHUB_CLIENTID: <github_client_id>
      # OAUTH_GITHUB_SECRET: <github_secret>

    depends_on:
      - db

```
