### ISSUE TITLE
dial tcp: lookup fider on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by pedropamn** [getfider/fider#716]
I'm not able to find what is wrong... Can someone help?

```
C:\fider>docker-compose up
Recreating fider_db_1 ... done
Recreating fider_app_1 ... done
Attaching to fider_db_1, fider_app_1
db_1   | LOG:  database system was shut down at 2019-01-08 23:23:13 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
app_1  | INFO [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk6
] Running migrations...
app_1  | INFO [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk6
] Found total of 54 migration files.
app_1  | ERROR [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk
6] Error Trace:
app_1  | - failed to get last migration record (app/pkg/dbx/migrate.go:52)
app_1  | - dial tcp: lookup fider on 127.0.0.11:53: no such host
fider_app_1 exited with code 1
app_1  | INFO [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk6
] Running migrations...
app_1  | INFO [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk6
] Found total of 54 migration files.
app_1  | ERROR [2019-01-08T23:27:39Z] [MIGRATE] [T2fCKYrw1zpgNCXaC1wmKjeAx4OsPsk
6] Error Trace:
app_1  | - failed to get last migration record (app/pkg/dbx/migrate.go:52)
app_1  | - dial tcp: lookup fider on 127.0.0.11:53: no such host
app_1  | INFO [2019-01-08T23:27:45Z] [MIGRATE] [w3KXi2vKTfk8EdmngSLJtts4bTuzbgHX
] Running migrations...
app_1  | INFO [2019-01-08T23:27:45Z] [MIGRATE] [w3KXi2vKTfk8EdmngSLJtts4bTuzbgHX
] Found total of 54 migration files.
app_1  | ERROR [2019-01-08T23:27:45Z] [MIGRATE] [w3KXi2vKTfk8EdmngSLJtts4bTuzbgH
X] Error Trace:
app_1  | - failed to get last migration record (app/pkg/dbx/migrate.go:52)
app_1  | - dial tcp: lookup fider on 127.0.0.11:53: no such host
app_1  | INFO [2019-01-08T23:27:50Z] [MIGRATE] [WvhQUh14plpAixnFc6fCOGCEcC4GvG2P
] Running migrations...
app_1  | INFO [2019-01-08T23:27:50Z] [MIGRATE] [WvhQUh14plpAixnFc6fCOGCEcC4GvG2P
] Found total of 54 migration files.
app_1  | ERROR [2019-01-08T23:27:50Z] [MIGRATE] [WvhQUh14plpAixnFc6fCOGCEcC4GvG2
P] Error Trace:
app_1  | - failed to get last migration record (app/pkg/dbx/migrate.go:52)
app_1  | - dial tcp: lookup fider on 127.0.0.11:53: no such host
Gracefully stopping... (press Ctrl+C again to force)
Stopping fider_app_1   ... done
Stopping fider_db_1    ... done
```

My docker-compose.yml

```
version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: production
      
      # Connection string to the PostgreSQL database. 
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://root:root@fider:5432/fider?sslmode=disable
      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: tXQhvSMWMS11qZ9euEhE6lf2ferf0FR6RYGd8iMXiTxxXtJ1XDVdTXPaLtV12ZGp

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: noreply@yourdomain.com

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      # EMAIL_SMTP_HOST: smtp.yourdomain.com
      # EMAIL_SMTP_PORT: 587
      # EMAIL_SMTP_USERNAME: user@yourdomain.com
      # EMAIL_SMTP_PASSWORD: s0m3p4ssw0rd
      
      ###
      # OPTIONAL
      #
      # Following settings are optional
      ###

      # Social OAuth: 
      # Read more on https://getfider.com/docs/configuring-oauth/

      # Facebook
      # OAUTH_FACEBOOK_APPID: <fb_app_id>
      # OAUTH_FACEBOOK_SECRET: <fb_app_secret>

      # Google
      # OAUTH_GOOGLE_CLIENTID: <google_app_id>
      # OAUTH_GOOGLE_SECRET: <google_app_secret>

      # GitHub
      # OAUTH_GITHUB_CLIENTID: <github_client_id>
      # OAUTH_GITHUB_SECRET: <github_secret>

    depends_on:
      - db
```
