### ISSUE TITLE
Changing Default Font

### ISSUE THREAD

**Issue by beraybentesen** [getfider/fider#722]
Can we change the default font for the self hosted solution?

**Comment by goenning** [comment]
You could use the Custom CSS option under Site Settings -> Advanced

**Comment by beraybentesen** [comment]
@import url('https://fonts.googleapis.com/css?family=Exo');
html {
Font-family: 'Exo', sans-serif;
}

this should work but did not.

**Comment by goenning** [comment]
Fider defines font-family on body element. Try this:

```css
@import url('https://fonts.googleapis.com/css?family=Exo');

html, body {
  font-family: 'Exo', sans-serif;
}
```
