### ISSUE TITLE
Unable to use localhost postgresql database instead of default db

### ISSUE THREAD

**Issue by nmummau** [getfider/fider#768]
OS: Ubuntu 18.04.3

I followed the [Hosting your own instance](https://getfider.com/docs/hosting-instance/) instructions and with that I successfully got my fider instance running. I can see the signup page at `http://localhost:9999/signup`. 

However **I would like to configure fider with my localhost postgresql database. So I'm trying to change my `DATABASE_URL` connection string**, following these instructions:
> The Docker Compose above defines two services: db and app. In case you're using an external Postgres database, remove db service and replace DATABASE_URL environment variable with your connection string.

I'm getting errors when attempting to use my local database. **Here's what I've done:**
- I have a postgresql instance running on localhost:5432.
- I removed the `db` service from the docker-compose.yml file.
- I changed the `DATABASE_URL` connection string to point to my local database.
- I removed the depends_on section fro the yml because without removing this I get this error if I don't: 
`ERROR: Service 'app' depends on service 'db' which is undefined.`

**After doing all this, I get this error consistently:**
```
$sudo docker-compose up
WARNING: The s variable is not set. Defaulting to a blank string.
Recreating fider_app_1 ... 
Recreating fider_app_1 ... done
Attaching to fider_app_1
app_1  | INFO [2019-08-16T05:18:14Z] [MIGRATE] [Lpn8Ap3VFvfeoHb8zWSuEVfR18jMZQkc] Running migrations...
app_1  | INFO [2019-08-16T05:18:14Z] [MIGRATE] [Lpn8Ap3VFvfeoHb8zWSuEVfR18jMZQkc] Found total of 61 migration files.
app_1  | ERROR [2019-08-16T05:18:14Z] [MIGRATE] [Lpn8Ap3VFvfeoHb8zWSuEVfR18jMZQkc] Error Trace: 
app_1  | - failed to get last migration record (app/pkg/dbx/migrate.go:52)
app_1  | - pq: Could not detect default username. Please provide one explicitly
fider_app_1 exited with code 1
```

**Here is a copy of my docker-compose.yml with all passwords obfuscated:**
```
version: '2'
services:
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment:
      # production for best performance, development for verbose logs
      GO_ENV: development

      # Connection string to the PostgreSQL database.
      DATABASE_URL: postgres://user:password@localhost:5432/fider?sslmode=disable
      
      JWT_SECRET: myjwtsecret

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: noreply@yourdomain.com

      # EMAIL
      EMAIL_SMTP_HOST: smtp.yourdomain.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: me@yourdomain.com
      EMAIL_SMTP_PASSWORD: password
```
