### ISSUE TITLE
No confirmation email arrives

### ISSUE THREAD

**Issue by balazser** [getfider/fider#829]
I'm trying to set up the service locally following the instructions found here:

> https://getfider.com/docs/hosting-instance/ 

but unfortunately, after trying to register I cannot receive any confirmation email then I always need to truncate the database.

I could send successfully a test email to the given account using cURL but not Fider.
Would you be so kind as to take a look at my configuration what do I do wrong or how could I debug it?

This works:
```
curl -s --user 'api:a974847c322c8a487b6876810c843b36-e470a504-48199704' \
    https://api.mailgun.net/v3/sandbox20db7f20a34c471b827bd516cfb4efd0.mailgun.org/messages \
    -F from='Excited User <excited@sandbox20db7f20a34c471b827bd516cfb4efd0.mailgun.org>' \
    -F to='xolicoh524@4tmail.net' \
    -F subject='Hello' \
    -F text='Testing some Mailgun awesomeness!'
```

This currently does not:
```
version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/dataZ
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: development 
      
      # Connection string to the PostgreSQL database. 
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable
      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: tXQhvSMWMS11qZ9euEhE6lf2ferf0FR6RYGd8iMXiTxxXtJ1XDVdTXPaLtV12ZGp

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: reply@sandbox20db7f20a34c471b827bd516cfb4efd0.mailgun.org

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      EMAIL_MAILGUN_API: key-a974847c322c8a487b6876810c843b36-e470a504-48199704 

      EMAIL_MAILGUN_DOMAIN: sandbox20db7f20a34c471b827bd516cfb4efd0.mailgun.org

    depends_on:
      - db


```
