### ISSUE TITLE
"Monkey testing" and Logging

### ISSUE THREAD

**Issue by esgn** [getfider/fider#843]
Hi,

Been testing with Fider 0.18.0 with your docker image and with homemade builds and I get a window.unhandledrejection error that pops in the logs table from time to time. Here is what my docker-compose file looks like for the record : 

```
version: '3'

services:

  fider-test-db:
    restart: always
    image: postgres
    container_name: fider_test_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fider
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: xxxxxx

  fider-test:
    restart: always
    image: getfider/fider:0.18.0
    container_name: fider_test
    ports:
      - "3000:3000"
    environment:
      GO_ENV: production
      LOG_LEVEL: ERROR
      DATABASE_URL: postgres://fider:xxxxxx@fider-test-db:5432/fider?sslmode=disable
      JWT_SECRET: somesecrethere
      EMAIL_NOREPLY: noreply@domain.com
      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: email@gmail.com
      EMAIL_SMTP_PASSWORD: password
    depends_on:
      - fider-test-db
```

Once everything is running, with a logged in user if I hit CTRL+F5 too often and to fast I get the following error in the logs table :

```
1 | WEB | ERROR | window.unhandledrejection: Failed to GET /_api/notifications/unread/total with body '<empty>' | {"Data": {"url": "http://lo
calhost:3000/", "stack": "l/</<@http://localhost:3000/assets/js/common.80bf9b6b78d4779132ab.js:1:3519\na/</<@http://localhost:3000/assets/js/ve
ndor.d76e26e216e01f0dbdb9.js:16:2489\na/<@http://localhost:3000/assets/js/vendor.d76e26e216e01f0dbdb9.js:16:2594\na@http://localhost:3000/asset
s/js/vendor.d76e26e216e01f0dbdb9.js:16:1411\n"}, "ContextID": "HkWzbwlNASRRcaQCxnVSXR7AtLQ0m5fY", "SessionID": "GXrWG3fYjofT22RmJUkkC0r2vj5AqCl
4aTOz4bNZMtAa3GK6", "UserAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"} | 2020-02-08 13:53:39.618879+0
0
```

As I want to prevent the database from being filled with these errors, I'm asking myself the following questions :

- Is this error common ? Is it fixable ? I'll try and look into it if I get the time
- Is there a way to deactivate database logging and move back to a more traditional file logging ?

Thanks in advance,
