### ISSUE TITLE
Problems with smpt

### ISSUE THREAD

**Issue by MrLivixx** [getfider/fider#890]
Hi, I have a problem with smtp sending emails.
I specified the username, server address, and password with the port.
And during the test sending, nothing happens to me.
As I found out later, my mail server requires ssl, and how do I make sure that emails are sent? 
I have enabled an ssl certificate.
**docker-compose.yml**
```yml
version: '2'
services:
  app:
    restart: always
    image: getfider/fider:stable
    network_mode: host
    volumes:
      - /fider:/app/etc
    environment:
      GO_ENV: production
      DATABASE_URL: postgres://ip:5432/fider?user=user&password=pass&sslmode=disable      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: secret
      EMAIL_NOREPLY: feedback@dreambot.ml
      EMAIL_SMTP_HOST: smtp.yandex.ru
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USERNAME: feedback@dreambot.ml
      EMAIL_SMTP_PASSWORD: password
```
**fider folder**
![image](https://user-images.githubusercontent.com/54632865/99552999-b022bb00-29ce-11eb-810c-08dfb90de70e.png)

**Comment by javierguzman** [comment]
I am just trying to get Fider up and running but as far as I can see in the documentation you need to have these two environment variables:
SSL_CERT
SSL_CERT_KEY

**Comment by mipapo** [comment]
> I am just trying to get Fider up and running but as far as I can see in the documentation you need to have these two environment variables:
> SSL_CERT
> SSL_CERT_KEY

This is only for making Fider available via https

> As I found out later, my mail server requires ssl, and how do I make sure that emails are sent?

I think this is currently not working. 
Looking at https://github.com/getfider/fider/blob/master/app/services/email/smtp/smtp.go#L102
`c, err := gosmtp.Dial(serverAddress)`

Could be replaced by something like this
```
tlsconfig := &tls.Config {
  InsecureSkipVerify: true,
  ServerName: smtpServer.host,
}

conn, err := tls.Dial(“tcp”, smtpServer.ServerName(), tlsconfig)
if err != nil {
  log.Panic(err)
}
  
client, err := gosmtp.NewClient(conn, smtpServer.host)
if err != nil {
  log.Panic(err)
}
```

https://asitdhal.medium.com/golang-sendmail-sending-mail-through-net-smtp-package-5cadbe2670e0

**Comment by goenning** [comment]
I heard many times people having problems with smtp, so I’m open for improvements on this area.

Is it safe to set InsecureSkipVerify to true?

**Comment by mipapo** [comment]
> I heard many times people having problems with smtp, so I’m open for improvements on this area.
> 
> Is it safe to set InsecureSkipVerify to true?

If I'm not totally wrong it should not be set in production to true. And I wonder  - as long as the server uses a valid Certificates which is known in the systems root ca sending mails should not fail.

**Comment by goenning** [comment]
@MrLivixx  can you check if the new environment variable introduced on this PR ( #926 ) fixes the problem? You can now disable STARTLS.

Please reopen if the problem persists.

**Comment by MrLivixx** [comment]
It still doesn't work, I changed docker-compose and now it looks like this.
```yml
version: '2'
services:
  app:
    restart: always
    image: getfider/fider:stable
    network_mode: host
    volumes:
      - /fider:/app/etc
    environment:
      HOST_DOMAIN: feedback.dreambot.ml
      GO_ENV: production
      DATABASE_URL: postgres://ip:5432/fider?user=postgres&password=pass&sslmode=disable      
      JWT_SECRET: secret
      EMAIL_NOREPLY: feedback@dreambot.ml
      EMAIL_SMTP_HOST: smtp.yandex.ru
      EMAIL_SMTP_PORT: 465
      EMAIL_SMTP_USERNAME: feedback@dreambot.ml
      EMAIL_SMTP_PASSWORD: pswd
```
 i used nginx proxy
 
 error logs: 
 ```
 app_1  | ERROR [2021-03-31T11:07:30Z] [WEB] [UTMNCC1feWdXmhzdgDCe5IscmTPz6eqm] Error Trace: 
app_1  | - app/middlewares/panic.go:18
app_1  | - goroutine 130 [running]:
app_1  | runtime/debug.Stack(0x1c98f40, 0xc00005c2a0, 0x0)
app_1  |        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
app_1  | github.com/getfider/fider/app/pkg/errors.Panicked(0x1a35500, 0xc00005c2a0, 0xc00005c2a0, 0x0)
app_1  |        /server/app/pkg/errors/errors.go:40 +0xe9
app_1  | github.com/getfider/fider/app/middlewares.CatchPanic.func1.1.1(0xc0003d2620)
app_1  |        /server/app/middlewares/panic.go:18 +0x5a
app_1  | panic(0x1a35500, 0xc00005c2a0)
app_1  |        /usr/local/go/src/runtime/panic.go:965 +0x1b9
app_1  | github.com/getfider/fider/app/services/email/smtp.sendMail(0x1ca72a8, 0xc0003d2620, 0xc000084e80)
app_1  |        /server/app/services/email/smtp/smtp.go:94 +0x180e
app_1  | reflect.Value.call(0x1a1daa0, 0x1b66e90, 0x13, 0x1aff5fa, 0x4, 0xc00020cd70, 0x2, 0x2, 0x19c5668, 0x8, ...)
app_1  |        /usr/local/go/src/reflect/value.go:476 +0x8e7
app_1  | reflect.Value.Call(0x1a1daa0, 0x1b66e90, 0x13, 0xc00020cd70, 0x2, 0x2, 0xc0001d1650, 0xc00039eb00, 0x203000)
app_1  |        /usr/local/go/src/reflect/value.go:337 +0xb9
app_1  | github.com/getfider/fider/app/pkg/bus.Publish(0x1ca72a8, 0xc0003d2620, 0xc00020ce50, 0x1, 0x1)
app_1  |        /server/app/pkg/bus/bus.go:152 +0x439
app_1  | github.com/getfider/fider/app/handlers/apiv1.SendSampleInvite.func1(0xc0003d2620, 0x1a10d00, 0xc0001d1570)
app_1  |        /server/app/handlers/apiv1/invite.go:32 +0x685
app_1  | github.com/getfider/fider/app/middlewares.IsAuthorized.func1.1(0xc0003d2620, 0x1a10d00, 0xc0001d1560)
app_1  |        /server/app/middlewares/auth.go:27 +0xc8
app_1  | github.com/getfider/fider/app/middlewares.IsAuthenticated.func1.1(0xc0003d2620, 0x1a10d00, 0xc0001d1550)
app_1  |        /server/app/middlewares/auth.go:15 +0x89
app_1  | github.com/getfider/fider/app/middlewares.CheckTenantPrivacy.func1.1(0xc0003d2620, 0x1a10d00, 0xc0001d1540)
app_1  |        /server/app/middlewares/tenant.go:124 +0xa2
app_1  | github.com/getfider/fider/app/middlewares.BlockLockedTenants.func1.1(0xc0003d2620, 0x1a10d00, 0xc0001d1530)
app_1  |        /server/app/middlewares/tenant.go:143 +0x1ab
app_1  | github.com/getfider/fider/app/middlewares.BlockPendingTenants.func1.1(0xc0003d2620, 0x1a10d00, 0xc0001d1520)
app_1  |        /server/app/middlewares/tenant.go:112 +0x133
app_1  | github.com/getfider/fider/app/middlewares.RequireTenant.func1.1(0xc0003d2620, 0xc0000ab880, 0xc0001d14f0)
app_1  |        /server/app/middlewares/tenant.go:97 +0x19f
app_1  | github.com/getfider/fider/app/middlewares.User.func1.1(0xc0003d2620, 0xc00002c00c, 0x14)
app_1  |        /server/app/middlewares/user.go:116 +0xea
app_1  | github.com/getfider/fider/app/middlewares.SingleTenant.func1.1(0xc0003d2620, 0xc0000e1a40, 0x1a10d00)
app_1  |        /server/app/middlewares/tenant.go:42 +0x13c
app_1  | github.com/getfider/fider/app/middlewares.WebSetup.func1.1(0xc0003d2620, 0xc0000cf6e0, 0xc0000cf608)
app_1  |        /server/app/middlewares/setup.go:107 +0x75c
app_1  | github.com/getfider/fider/app/middlewares.Maintenance.func1.1(0xc0003d2620, 0xc0000e1a40, 0xc0000cf6b0)
app_1  |        /server/app/middlewares/maintenance.go:15 +0x476
app_1  | github.com/getfider/fider/app/middlewares.Session.func1.1(0xc0003d2620, 0x0, 0x1affa4e)
app_1  |        /server/app/middlewares/session.go:21 +0x1ee
app_1  | github.com/getfider/fider/app/middlewares.Compress.func1.1(0xc0003d2620, 0xc0000e1980, 0x1b098c1)
app_1  |        /server/app/middlewares/compress.go:53 +0x5c6
app_1  | github.com/getfider/fider/app/middlewares.Secure.func1.1(0xc0003d2620, 0x0, 0x0)
app_1  |        /server/app/middlewares/security.go:25 +0x546
app_1  | github.com/getfider/fider/app/middlewares.CatchPanic.func1.1(0xc0003d2620, 0x0, 0x0)
app_1  |        /server/app/middlewares/panic.go:32 +0x5e
app_1  | github.com/getfider/fider/app/pkg/web.(*Engine).handle.func1(0x1ca51f0, 0xc0003d2540, 0xc00039eb00, 0x0, 0x0, 0x0)
app_1  |        /server/app/pkg/web/engine.go:234 +0x138
app_1  | github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0000861e0, 0x1ca51f0, 0xc0003d2540, 0xc00039eb00)
app_1  |        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
app_1  | net/http.serverHandler.ServeHTTP(0xc0000ea000, 0x1ca51f0, 0xc0003d2540, 0xc00039eb00)
app_1  |        /usr/local/go/src/net/http/server.go:2887 +0xa3
app_1  | net/http.(*conn).serve(0xc0001dcc80, 0x1ca7040, 0xc000084b80)
app_1  |        /usr/local/go/src/net/http/server.go:1952 +0x8cd
app_1  | created by net/http.(*Server).Serve
app_1  |        /usr/local/go/src/net/http/server.go:3013 +0x39b
app_1  |  (app/pkg/errors/errors.go:40)
app_1  | - github.com/getfider/fider/app/services/email/smtp.sendMail:94 (app/pkg/errors/errors.go:39)
app_1  | - failed to send email with template invite_email (app/services/email/smtp/smtp.go:94)
app_1  | - EOF
```
