### ISSUE TITLE
Problem deleting and saving edited suggestions when using HTTPS (Turned into a discussion about Caddy + Fider)

### ISSUE THREAD

**Issue by StrangeRanger** [getfider/fider#905]
I have everything set up through a reverse proxy on apache2, using certbot to provide an SSL certificate to use HTTPS. Whenever I connect to my website through the domain name (which forces HTTPS) and try to edit or delete feedback, I'm prompted with the following errors (which are shown from the docker logs and web browser console). This doesn't seem to be a problem when I access my website via its IP Address through HTTP. I haven't set up SSL/HTTPS through the docker file yet. Could this be the reason why I'm having this problem? If so, could I get help setting it up? I am having a hard time doing it, even with the instructions here: https://getfider.com/docs/how-to-enable-ssl/.
<img width="1792" alt="Screen Shot 2021-02-06 at 9 13 59 PM" src="https://user-images.githubusercontent.com/30395560/107137327-60160f00-68c0-11eb-9c61-a487f12e9df6.png">
<img width="1787" alt="Screen Shot 2021-02-06 at 9 14 38 PM" src="https://user-images.githubusercontent.com/30395560/107137329-61dfd280-68c0-11eb-873d-c0a2af1ed588.png">

**Comment by mipapo** [comment]
So maybe just a hint for the ssl via docker:
If you already have requested the certificate for the domain:
```
    volumes:
      - /etc/letsencrypt/live/<your-url>/fullchain.pem:/app/etc/fullchain.pem
      - /etc/letsencrypt/live/<your-url>/privkey.pem:/app/etc/privkey.pem
    ports:
      - "80:3000"
      - "443:3000"
```

**Comment by StrangeRanger** [comment]
I'll have to try that. Though I was able to get around this problem by running fider with the Caddy web server.

**Comment by goenning** [comment]
Using Caddy or any other ReverseProxy should be fine, especially for HTTPS termination.

The response code is coming back as 401, which to me sounds like the request went through to Fider, but it did not have the authentication Cookie. Is there something missing on your Caddy configs maybe?

**Comment by StrangeRanger** [comment]
Apologies for the late response @goenning. I'm unsure what you mean. I'm not getting a 401 status from the site? 

```
❯ http https://feedback.randomserver.xyz
HTTP/1.1 200 OK
CF-Cache-Status: DYNAMIC
CF-RAY: 6301b03ead42146e-SEA
Connection: keep-alive
Content-Encoding: gzip
Content-Security-Policy: base-uri 'self'; default-src 'self'; style-src 'self' 'nonce-JnOOjbt4EqOVp8aUKpLFVhofls04ljCa' https://fonts.googleapis.com ; script-src 'self' 'nonce-JnOOjbt4EqOVp8aUKpLFVhofls04ljCa' https://cdn.polyfill.io https://js.stripe.com https://www.google-analytics.com ; img-src 'self' https: data: ; font-src 'self' https://fonts.gstatic.com data: ; object-src 'none'; media-src 'none'; connect-src 'self' https://www.google-analytics.com https://ipinfo.io https://js.stripe.com ; frame-src 'self' https://js.stripe.com
Content-Type: text/html; charset=utf-8
Date: Mon, 15 Mar 2021 00:40:06 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
NEL: {"max_age":604800,"report_to":"cf-nel"}
Referrer-Policy: no-referrer-when-downgrade
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=O7Ma0%2BW1nXI%2FIaWFFTD4r0udBnFoH4n4KDnNEyM3mZjaR%2Fo63nt%2FNiJD95O%2Fqlnj32fPEXpIDgdGX7rwEi60i5i62KfPqj1wQ7KxH%2FRToSNBRWNVXi9TLLLu"}],"max_age":604800}
Server: cloudflare
Set-Cookie: __cfduid=d4c5697291474e87a21ae9179e1240bde1615768806; expires=Wed, 14-Apr-21 00:40:06 GMT; path=/; domain=.randomserver.xyz; HttpOnly; SameSite=Lax; Secure
Set-Cookie: user_session_id=w1PXugcwZowhcD9tH5SlPfW5ikp0clJbZPnVqjZUaBGzzxYk; Path=/; Expires=Tue, 15 Mar 2022 00:40:06 GMT; HttpOnly; Secure
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
cf-request-id: 08d4ec7b2d0000146eaa0b6000000001
```

**Comment by goenning** [comment]
I misunderstood your comment. Are you saying it's solved now using Caddy?

Would also be interested in knowing what problem you're having with https://getfider.com/docs/how-to-enable-ssl/ so we can improve it

**Comment by StrangeRanger** [comment]
I was able to resolve the problem by using Caddy. I was having this problem when trying to set up getfider with the latest version of apache, using its reverse proxy.

When it comes to https://getfider.com/docs/how-to-enable-ssl/, the problem I have is that the docs aren't very specific. It comes across as though the end-user needs to be experienced with docker, lets-encrypt, and even set up an external database.

"Fider's Docker image expects both files to be available on `/app/etc`." Where is `/app/etc/`? Is it somewhere in the `pg_data` directory (I can't find it) or is it somewhere in the Docker image (how do you even access it?)?

In addition, the docs recommend you set up an external database instead of using a database inside the docker image unless you know how to manage a database inside docker. But the docs never even explain how to prepare the external database. I had to use external documentation to figure how to set up the external database, and even then, the docker image didn't want to communicate with the database.

I wish the docs would be a bit more descriptive and wouldn't just give the minimum information needed. If anything, it would be nice if a link was provided to instructions describing how to do certain things that getfider needs set up to work.

**Comment by mipapo** [comment]
`/app/etc/` is in the docker container. 
That's what you see here
```
    volumes:
      - /etc/letsencrypt/live/<your-url>/fullchain.pem:/app/etc/fullchain.pem
      - /etc/letsencrypt/live/<your-url>/privkey.pem:/app/etc/privkey.pem
  ```

> In addition, the docs recommend you set up an external database instead of using a database inside the docker image unless you know how to manage a database inside docker. But the docs never even explain how to prepare the external database. I had to use external documentation to figure how to set up the external database, and even then, the docker image didn't want to communicate with the database.

In my opinion I don't think this belongs to the documentation of fider. This is docker knowledge and depends how your docker setup looks like so I don't see this is the task of fiders documentation.

**Comment by StrangeRanger** [comment]
> /app/etc/ is in the docker container.
> That's what you see here
>	```
>    volumes:
>      - /etc/letsencrypt/live/<your-url>/fullchain.pem:/app/etc/fullchain.pem
>      - /etc/letsencrypt/live/<your-url>/privkey.pem:/app/etc/privkey.pem
>    ```

The docker container is created by creating a docker volume, right? Or am I incorrect?

> In my opinion I don't think this belongs to the documentation of fider. This is docker knowledge and depends how your docker setup looks like so I don't see this is the task of fiders documentation.

Fider requires docker to run. So if you have no knowledge of docker and there's not even the most basic instructions on configuring and setting everything up, then you SOL. I understand that you can also try setting it up via Heroku, but I tried that a total of three times, and every time, the build failed.

**Comment by spencerflagg** [comment]
> I was able to resolve the problem by using Caddy. I was having this problem when trying to set up getfider with the latest version of apache, using its reverse proxy.

Can you be more specific about how you were able to solve the problem using Caddy? I'd really appreciate any info you can give me. I just got a Fider instance spun up, and was attempting to use Caddy's reverse proxy to expose Fider to port 80, but I couldn't figure out how to combine Caddy with the info in Fider's SSL docs.

Thanks in advance!

**Comment by StrangeRanger** [comment]
@spencerflagg From my understanding, and from the recent update to the Fider docs, if you are using a reverse proxy, I don't think it's necessary to configure the Fider SSL. This is due to the fact that Caddy will automatically force Fider to be routed through HTTPS using an SSL certificate that it created, so there is no reason for Fider to handle any the SSL certificates. That's my understanding at least, and I haven't had any problems so far.

With that said, I didn't do anything special to configure and get Fider to work with Caddy.
I simply added the following lines to `/etc/caddy/Caddyfile`:

```conf
feedback.randomserver.xyz {
    reverse_proxy 127.0.0.1:9999
}
```

You'll want to replace `feedback.randomserver.xyz` with your website's address. Port 9999 is the default port that Fider runs on. And since your running a reverse proxy, the only ports you really need open is 80 and 433.

I hope this helps.

**Comment by spencerflagg** [comment]
@StrangeRanger Interesting. I don't quite have it working yet, but I'm glad Caddy is supposed to be such an easy lift.


For clarification, my `docker-compose.yml` has these ports...
```
ports:
      - "9999:3000"
```

My Caddyfile looks like this...
```
mydomain.com {
  respond * "mydomain.com is working"
}

test.mydomain.com {
  respond * "test.mydomain.com is working"
}

fider.mydomain.com {
  reverse_proxy 127.0.0.1:9999
}
```

**mydomain.com** returns correctly, **test.mydomain.com** returns correctly, but **fider.mydomain.com** throws a 502.
Only if I hack the URL and try to hit, exactly, **http://fider.mydomain.com:3000** then the site gets served.

Any thoughts?

**Comment by StrangeRanger** [comment]
@spencerflagg Their having two separate .yml files shouldn't affect anything negatively. 

I have the same ports in my `docker-compose.yml`.

What version of the `docker-compose.yml` did you set Fider up with? Refer to [this issue](https://github.com/getfider/fider/issues/927#issue-838130841) and at the pictures I posted.

**Comment by spencerflagg** [comment]
I started with the new version (black bkg on site), but was running into issues connecting to postgres. At @goenning's recommendation that I link containers [here](https://github.com/getfider/fider/issues/922) I shifted to the old version (gray bkg).

**Comment by spencerflagg** [comment]
Getting `dial tcp 127.0.0.1:9999: connect: connection refused` in the Caddy container logs.

**Comment by StrangeRanger** [comment]
Yea, I found a problem in the new configurations so I've been using the older one as well.

@spencerflagg Do you mind sending your `docker-compose.yml` (obviously removing sensitive info)? I want to compare our configurations. I'll send mine down below.

**Comment by StrangeRanger** [comment]
```yml
version: '2'
services:
  db:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/fider/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: somepassword 	# Modified for security

  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    environment:
      ###
      # REQUIRED
      #
      # All these settings are required
      ###

      # Use production for best performance
      # Use development for verbose logs
      GO_ENV: production

      # Public host address (required)
      HOST_DOMAIN: feedback.randomserver.xyz
      
      # Connection string to the PostgreSQL database. 
      # This example uses the Docker service defined above
      DATABASE_URL: postgres://fider:somepassword@db:5432/fider?sslmode=disable  # Password modified for security
      
      # CHANGE THIS! You can generate a strong secret at https://randomkeygen.com/
      JWT_SECRET: somepassword	# Modified for security

      # From which account e-mails will be sent (required)
      EMAIL_NOREPLY: noreply@randomserver.xyz

      ###
      # EMAIL
      #
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: email@gmail.com  # Modified for privacy
      EMAIL_SMTP_PASSWORD: somepassword		# Modified for security
      
      ###
      # OPTIONAL
      #
      # Following settings are optional
      ###

      # Social OAuth: 
      # Read more on https://getfider.com/docs/configuring-oauth/

      # Facebook
      # OAUTH_FACEBOOK_APPID: <fb_app_id>
      # OAUTH_FACEBOOK_SECRET: <fb_app_secret>

      # Google
      # OAUTH_GOOGLE_CLIENTID: <google_app_id>
      # OAUTH_GOOGLE_SECRET: <google_app_secret>

      # GitHub
      # OAUTH_GITHUB_CLIENTID: <github_client_id>
      # OAUTH_GITHUB_SECRET: <github_secret>

    depends_on:
      - db
```
