### ISSUE TITLE
Container unhealthy with AUTO_SSL = "true"

### ISSUE THREAD

**Issue by davidebonavita** [getfider/fider#940]
Hello everybody,
I'm making some tests with Fider and it looks and works great as long as I use my own SSL certificate. It doesn't seem to work when I use the AUTO_SSL feature. The Container remains unhealthy although I don't see any errors in the logs:

```
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS                     PORTS                                       NAMES
cb70c84b444b   getfider/fider:stable   "/bin/sh -c './fider…"   8 minutes ago   Up 8 minutes (unhealthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->3000/tcp   fider_app_1
```

```
Attaching to fider_app_1
app_1  | INFO [2021-03-31T10:37:55Z] [MIGRATE] [3I2SjBZ82JYLRcDiSc8FdL3lSZUJsD8T] Running migrations...
app_1  | INFO [2021-03-31T10:37:55Z] [MIGRATE] [3I2SjBZ82JYLRcDiSc8FdL3lSZUJsD8T] Found total of 63 migration files.
app_1  | INFO [2021-03-31T10:37:55Z] [MIGRATE] [3I2SjBZ82JYLRcDiSc8FdL3lSZUJsD8T] Current version is 201904091921
app_1  | INFO [2021-03-31T10:37:55Z] [MIGRATE] [3I2SjBZ82JYLRcDiSc8FdL3lSZUJsD8T] Migrations are already up to date.
app_1  | INFO [2021-03-31T10:37:55Z] [WEB] [xqbicMy3hkAPqId98pt3I248tSw2UIs3] Application is starting
app_1  | INFO [2021-03-31T10:37:55Z] [WEB] [xqbicMy3hkAPqId98pt3I248tSw2UIs3] GO_ENV: production
app_1  | INFO [2021-03-31T10:37:55Z] [WEB] [xqbicMy3hkAPqId98pt3I248tSw2UIs3] https (auto ssl) server started on :3000
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 3.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 0.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 1.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 2.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 6.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 5.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 7.
app_1  | INFO [2021-03-31T10:37:55Z] [BGW] [Xk1sbOPyDkV4ttk9bbvb7KNewVzJSwdh] Starting worker 4.
```

This is my docker-compose.yml file, I've edited out my personal details:

```
version: '2'
services:
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "80:80"
      - "443:3000"
    environment:
      # Public Host name or IP Address
      HOST_DOMAIN: XXXXXXXXXXXX
      SSL_AUTO: "true"

      OAUTH_GOOGLE_CLIENTID: XXXXXXXXXXXX
      OAUTH_GOOGLE_SECRET: XXXXXXXXXXXX

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://XXXXXXXXXXXX@XXXXXXXXXXXX:5432/fider?sslmode=disable
      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET: XXXXXXXXXXXX
      # From which account e-mails will be sent
      EMAIL_NOREPLY: XXXXXXXXXXXX
      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: XXXXXXXXXXXX
      EMAIL_SMTP_PASSWORD: XXXXXXXXXXXX
```

**Comment by goenning** [comment]
Can you set LOG_LEVEL=DEBUG on Docker compose to see if we get more info from it?

**Comment by davidebonavita** [comment]
> Can you set LOG_LEVEL=DEBUG on Docker compose to see if we get more info from it?

Hello!
If I got it right it doesn't say much:

```
davide@fider:/var/fider$ sudo docker-compose --log-level DEBUG up -d  --force-recreate    
Using configuration files: ./docker-compose.yml                                           
WARNING: The B variable is not set. Defaulting to a blank string.                         
Removing fider_app_1                                                                      
Pending: {<Service: app>}                                                                 
Starting producer thread for <Service: app>                                               
Recreating 86228d61f0d2_fider_app_1 ...                                                   
Pending: {<Container: 86228d61f0d2_fider_app_1 (86228d)>}                                 
Starting producer thread for <Container: 86228d61f0d2_fider_app_1 (86228d)>               
Added config hash: 1f63a7341719c84864da0fd136a123f7facf98debbd7991f0447e7d9aa3fbcdb       
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Pending: set()                                                                            
Recreating 86228d61f0d2_fider_app_1 ... done                                              
Pending: set()                                                                            
Finished processing: <Service: app>                                                       
Pending: set()                      
 ```                 

```
davide@fider:/var/fider$ sudo docker-compose logs app
Attaching to fider_app_1
app_1  | INFO [2021-04-06T11:30:47Z] [MIGRATE] [HWW7A0uPz5tpWF8sxPTwQJzbsn8FOvSQ] Running migrations...
app_1  | INFO [2021-04-06T11:30:47Z] [MIGRATE] [HWW7A0uPz5tpWF8sxPTwQJzbsn8FOvSQ] Found total of 63 migration files.
app_1  | INFO [2021-04-06T11:30:47Z] [MIGRATE] [HWW7A0uPz5tpWF8sxPTwQJzbsn8FOvSQ] Current version is 201904091921
app_1  | INFO [2021-04-06T11:30:47Z] [MIGRATE] [HWW7A0uPz5tpWF8sxPTwQJzbsn8FOvSQ] Migrations are already up to date.
app_1  | INFO [2021-04-06T11:30:47Z] [WEB] [B2LaLdGaBmotxSkyCc0Qo5XOgpH0WkUb] Application is starting
app_1  | INFO [2021-04-06T11:30:47Z] [WEB] [B2LaLdGaBmotxSkyCc0Qo5XOgpH0WkUb] GO_ENV: production
app_1  | INFO [2021-04-06T11:30:47Z] [WEB] [B2LaLdGaBmotxSkyCc0Qo5XOgpH0WkUb] https (auto ssl) server started on :3000
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 0.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 4.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 5.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 6.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 7.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 1.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 3.
app_1  | INFO [2021-04-06T11:30:47Z] [BGW] [6G6jD6nJirHFirIV0xNjqBjtLYQWwhc5] Starting worker 2.
```

**Comment by goenning** [comment]
I should have been more specific, add it to your env variables, like this:
```
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "80:3000"
    environment:
      HOST_DOMAIN: ...
      LOG_LEVEL: DEBUG
      ...
```

**Comment by davidebonavita** [comment]
Sorry, my bad.
It doesn't seem to add any useful data I'm afraid, I left it running for about 10 minutes
```
davide@fider:/var/fider$ sudo docker-compose logs app
Attaching to fider_app_1
app_1  | INFO [2021-04-07T14:31:02Z] [MIGRATE] [g0xefS4ysyEbEMyBoX881bv22ykOwLk9] Running migrations...
app_1  | INFO [2021-04-07T14:31:02Z] [MIGRATE] [g0xefS4ysyEbEMyBoX881bv22ykOwLk9] Found total of 63 migration files.
app_1  | INFO [2021-04-07T14:31:02Z] [MIGRATE] [g0xefS4ysyEbEMyBoX881bv22ykOwLk9] Current version is 201904091921
app_1  | INFO [2021-04-07T14:31:02Z] [MIGRATE] [g0xefS4ysyEbEMyBoX881bv22ykOwLk9] Migrations are already up to date.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'log.Console' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'blobstorage.SQL' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'email.SMTP' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'httpclient.HTTP' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'log.SQL' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'OAuth.HTTP' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] Service 'sqlstore.PostgreSQL' has been initialized.
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] deleting notifications more than 1 year old
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] DELETE FROM notifications WHERE CREATED_AT <= NOW() - INTERVAL '365 days' [] executed in 0ms
app_1  | DEBUG [2021-04-07T14:31:02Z] [BOOTSTRAP] a total of 0 notifications were deleted
app_1  | INFO [2021-04-07T14:31:02Z] [WEB] [Zy5rdycpyqKKToZc0mXVUJHS2Q0Zb4Mp] Application is starting
app_1  | INFO [2021-04-07T14:31:02Z] [WEB] [Zy5rdycpyqKKToZc0mXVUJHS2Q0Zb4Mp] GO_ENV: production
app_1  | INFO [2021-04-07T14:31:02Z] [WEB] [Zy5rdycpyqKKToZc0mXVUJHS2Q0Zb4Mp] https (auto ssl) server started on :3000
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 3.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 6.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 7.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 4.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 5.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 0.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 2.
app_1  | INFO [2021-04-07T14:31:02Z] [BGW] [bTylrDmZH5uv5qThJoz2H59oRdkpXtzJ] Starting worker 1.
app_1  | DEBUG [2021-04-07T14:31:50Z] [???] SELECT file, content_type, size FROM blobs WHERE key = $1 AND (tenant_id = $2 OR ($2 IS NULL AND tenant_id IS NULL)) [autocert/XXXXXXXX {0 false}] executed in 1ms
app_1  | DEBUG [2021-04-07T14:31:50Z] [???] SELECT file, content_type, size FROM blobs WHERE key = $1 AND (tenant_id = $2 OR ($2 IS NULL AND tenant_id IS NULL)) [autocert/acme_account+key {0 false}] executed in 0ms
app_1  | DEBUG [2021-04-07T14:31:51Z] [???]  INSERT INTO blobs (tenant_id, key, size, content_type, file, created_at, modified_at) VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (tenant_id, key) DO UPDATE SET size = $3, content_type = $4, file = $5, modified_at = $7  [{0 false} autocert/XXXXXXXX+token 862 application/x-pem-file [EDITED DATA] 2021-04-07 14:31:51.707525822 +0000 UTC m=+48.888125680 2021-04-07 14:31:51.707525822 +0000 UTC m=+48.888125680] executed in 0ms
```

**Comment by goenning** [comment]
1. Can you run docker-compose pull and try again? Just to be sure it’s running the latest version.
2. Does your VM have a firewall? If yes, open up port 80.

**Comment by goenning** [comment]
I tried this again today and here is what I did:

```
- created a digitalocean vm
- installed docker
- installed docker compose
- created /var/fider
- copied docker-compose
- changed HOST_DOMAIN to mydomain.com
- started the app
- open http://mydomain.com and it worked (no HTTPS)

At this stage HTTP was working.

- modified ports and environment as per docs
    ports:
      - "80:80"
      - "443:3000"
    environment:
      ...
      HOST_DOMAIN: mydomain.com
      SSL_AUTO: "true"


- open http://mydomain.com, it took 2 seconds and redirected me to https://mydomain.com with a Lets Encrypt certificate
```
