### ISSUE TITLE
[BUG] Page not found

### ISSUE THREAD

**Issue by andremoah** [getfider/fider#945]
**Self Hosted**
Using stable version

**Describe the bug**
Trying to run the docker-compose example with gmail stmp server as shown below

```
version: '2'
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd
  app:
    restart: always
    image: getfider/fider:stable
    ports:
      - "3000:3000"
    environment:
      # Public Host name or IP Address
      HOST_DOMAIN: 0.0.0.0:3000

      # Connection string to the PostgreSQL database
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@db:5432/fider?sslmode=disable

      # Generate a 512-bit secret here https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
      JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE

      # From which account e-mails will be sent
      EMAIL_NOREPLY: noreply@yourdomain.com

      ###
      # EMAIL
      # Either EMAIL_MAILGUN_* or EMAIL_SMTP_* is required
      ###

      # EMAIL_MAILGUN_API: key-yourkeygoeshere
      # EMAIL_MAILGUN_DOMAIN: yourdomain.com

      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: myemail@gmail.com
      EMAIL_SMTP_PASSWORD: myawsomepassword
```

**To Reproduce**
1. Just copy-paste the docker-compose (change the Gmail username / password)
2. docker-compose up
3. Try to register and get the email
4. Open the sent link

**Expected behavior**
Complete the setup registration

**Screenshots**
<img width="1440" alt="Screenshot 2021-04-19 at 23 37 27" src="https://user-images.githubusercontent.com/8550246/115312080-9dbcd100-a168-11eb-9728-582d1b0da3a0.png">

A 404 page is presented and no matter what I try to do it gets stuck forever there. I have tried pretty much everything and still, I can't run fider locally. 

Is there a way to create a default admin account skipping this email confirmation part? 

**Edit 25/4/2021**

Closing the issue as the error was from bad configuration in the docker-compose file
